name: Publish to Server

on:
    push:
        branches: [ main ]
    workflow_dispatch: 

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '22'
                
            - name: Install dependencies
              run: yarn install
              
            - name: Run linting
              run: yarn lint
            
            - name: rm node_modules
              run: rm -rf node_modules
    
    deploy:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

              
            - name: Upload files to server
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                rm: true
                source: "."
                target: "~/prod"
                
            - name: Deploy to server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    cd ~/prod
                    yarn install --prod
                    pm2 restart all
